# fly.toml app configuration file generated for spot-arb on 2025-07-14T01:09:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spot-arb'
primary_region = 'qro'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[services]]
internal_port = 8080
protocol = "tcp"
processes = ["app"]
auto_start_machines = true
auto_stop_machines = "off"
checks = []
